import os
import uuid
import json
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"

def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)

def write_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)

def signal_llm(text):
    prompt = f"""You are an AI content detection expert. Analyze the following text and determine whether it was written by a human or generated by AI.

Return ONLY a JSON object in this exact format, nothing else:
{{"ai_probability": 0.85, "reasoning": "one sentence explanation"}}

The ai_probability should be a float between 0.0 (definitely human) and 1.0 (definitely AI).

Text to analyze:
{text}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()
    result = json.loads(raw)
    return result["ai_probability"]

def signal_stylometric(text):
    import re
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) < 2:
        return 0.5

    # Sentence length variance
    lengths = [len(s.split()) for s in sentences]
    avg = sum(lengths) / len(lengths)
    variance = sum((l - avg) ** 2 for l in lengths) / len(lengths)

    # Type-token ratio (vocabulary diversity)
    words = text.lower().split()
    ttr = len(set(words)) / len(words) if words else 0.5

    # Punctuation density
    punct_count = sum(1 for c in text if c in '",;:()!?')
    punct_density = punct_count / len(text) if text else 0

    # Low variance + low TTR + low punctuation = more AI-like
    variance_score = max(0, 1 - (variance / 20))
    ttr_score = max(0, 1 - ttr)
    punct_score = max(0, 1 - (punct_density * 20))

    return round((variance_score + ttr_score + punct_score) / 3, 3)

def generate_label(confidence):
    if confidence >= 0.75:
        return "Likely AI-generated. This content was flagged as probably created by an AI writing tool. Confidence: High."
    elif confidence <= 0.40:
        return "Likely human-written. This content appears to have been written by a person. Confidence: High."
    else:
        return "Uncertain. Our system could not confidently determine whether this content was written by a human or AI. The author may appeal if this label is incorrect."

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    text = data.get("text", "")
    creator_id = data.get("creator_id", "")
    content_id = str(uuid.uuid4())

    llm_score = signal_llm(text)
    stylo_score = signal_stylometric(text)
    confidence = round((llm_score * 0.6) + (stylo_score * 0.4), 3)
    attribution = "likely_ai" if confidence >= 0.75 else "likely_human" if confidence <= 0.40 else "uncertain"
    label = generate_label(confidence)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "status": "classified"
    }
    entries = read_log()
    entries.append(entry)
    write_log(entries)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "llm_score": llm_score,
        "stylo_score": stylo_score
    })

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    content_id = data.get("content_id", "")
    reasoning = data.get("creator_reasoning", "")

    entries = read_log()
    found = False
    for entry in entries:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal_reasoning"] = reasoning
            entry["appeal_timestamp"] = datetime.now(timezone.utc).isoformat()
            found = True
            break

    if not found:
        return jsonify({"error": "content_id not found"}), 404

    write_log(entries)
    return jsonify({
        "message": "Appeal received",
        "content_id": content_id,
        "status": "under_review"
    })

@app.route("/log", methods=["GET"])
def get_log():
    return jsonify({"entries": read_log()})

if __name__ == "__main__":
    app.run(debug=True, port=5001)